appName: myhelmapp

port: 80
replicas: 4

configmap:
  name: myhelmapp-configmap-v1
  data:
    CUSTOM_HEADER: 'This app was deployed with helm!'

image:
  name: libinmathew/stunning-broccoli-flask-app
  tag: demo
