apiVersion: v1
kind: Service
metadata:
  name: bluegreen-nodejs-demo-preview
  labels:
    app: bluegreen-nodejs-demo
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: bluegreen-nodejs-demo