apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - port: 6000
    targetPort: 5000
    protocol: TCP
    name: flask-app
  selector:
    app: {{ .Values.deploymentName }}
    tier: frontend
  type: LoadBalancer
