replicaCount: 3
image:
  repository: libinmathew/stunning-broccoli-nodejs-app
  pullPolicy: Always
  tag: "prod"
service:
  type: LoadBalancer
  port: 80
  targetPort: 3000
  protocol: TCP
  name: node-app-service
resources: {}
limits:
    cpu: 200m
    memory: 256Mi
requests:
    cpu: 400m
    memory: 512Mi
autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80