apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name.appname}}-preview
  annotations:
    ingress.kubernetes.io/proxy-body-size: 100M
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/app-root: /
spec:
 rules:
  - host: nodedev.intrastream.cyou
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.name.appname}}-preview 
            port:
              number: {{ .Values.service.port }}