apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.name.appname}}
  labels:
    app: {{ .Values.name.appname}}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.name.appname}}
  template:
    metadata:
      labels:
        app: {{ .Values.name.appname}}
    spec:
        containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
        imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
  strategy:
    blueGreen:
        autoPromotionEnabled: false
        activeService: {{ .Values.name.appname}}
        previewService: {{ .Values.name.appname}}-preview