---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "helm-nodejs-app.fullname" . }}
  labels:
    app: {{ template "helm-nodejs-app.name" . }}
    chart: {{ template "helm-nodejs-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ template "helm-nodejs-app.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "helm-nodejs-app.fullname" . }}-preview
  labels:
    app: {{ template "helm-nodejs-app.name" . }}
    chart: {{ template "helm-nodejs-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ template "helm-nodejs-app.name" . }}
    release: {{ .Release.Name }}