apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }} 
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec: # Pod spec
      
      containers:
      - name: mycontainer
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        # env:
        #   - name: REGISTRY_HTTP_TLS_CERTIFICATE
        #     value: "/certs/cert.pem"
        #   - name: REGISTRY_HTTP_TLS_KEY
        #     value: "/certs/privkey.pem"
        resources:
          requests:
            memory: "128Mi" 
            cpu: "500m"    # 500milliCPUs (1/2 CPU)
          limits:
            memory: "256Mi"
            cpu: "600m"   
      imagePullSecrets:
      - name: quayrepo
