apiVersion: v1
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmludHJhc3RyZWFtLmN5b3UiOiB7CiAgICAgICJhdXRoIjogImJHbGlhVzV0WVhSb1pYYzZjRFowVUd0NlZFVndkSHBUVm5OQlIwWmlNV2RuTTBacU5Ua3JabEpJVUdobE1sQlFPR1ZVYVN0cmQzQjBUMmhvSzFoVmFqSXdXR3BCZVdOVlNtbGxidz09IiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
kind: Secret
metadata:
  creationTimestamp: null
  name: quayrepo
type: kubernetes.io/dockerconfigjson
