apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
  annotations:
    argocd.argoproj.io/sync-options: Validate=false  
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec: # Pod spec
      # imagePullSecrets:
      # - name: nodejsappsecret
      containers:
      - name: mycontainer
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      imageCredentials:
        name: harbor_credentials
        registry: harbor.intrastream.cyou
        username: demo
        password: Demo@123  
        # ports:
        # - containerPort: 80
        resources:
          requests:
            memory: "128Mi" 
            cpu: "500m"    # 500milliCPUs (1/2 CPU)
          limits:
            memory: "256Mi"
            cpu: "600m"
