apiVersion: v1
kind: Secret
metadata:
  name: nodejsappsecret
data:
  # Harbor Service secrets
  harbor-username: {{ .Values.harborRepositoryInfo.username }}
  harbor-password: {{ .Values.harborRepositoryInfo.password }}
  harbor-server: {{ .Values.harborRepositoryInfo.server }}
  harbor-email: {{ .Values.harborRepositoryInfo.emailid }}
type: dockerconfigjson